- hosts: firepress_hosts
  gather_facts: no
  become: True
  pre_tasks:
    - name: 'install python2'
      raw: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade && apt-get -y install python-simplejson

- name: All roles
  hosts: firepress_hosts
  become: True
  roles:
    - { role: debops.bootstrap,                 tags: [ "role:bootstrap" ] }
    - { role: debops.core,                      tags: [ "role::core" ] }
    - { role: debops.fail2ban,                  tags: [ "role::fail2ban" ] }
    - { role: debops.ntp,                       tags: [ "role::ntp" ] }
    - { role: debops.swapfile,                  tags: [ "role::swapfile" ] }
    - { role: debops.docker,                    tags: [ "role::docker" ] }
    - { role: ufw,                              tags: [ "role::ufw" ] }
    - { role: commons,                          tags: [ "role::commons" ] }
  tasks:
    - name: reboot the system before install
      become: yes
      shell: sleep 2 && /sbin/shutdown -r now "reboot the system before install"
      async: 1
      poll: 0

    - name: waiting for server to come back
      local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=30 timeout=1000
      sudo: false
